@startuml
class App{
    +assignment41_input.txt
    ---
    + Scanner f
    + ArrayList<String> people
    ---
    {method} + main(String[] args) throws FileNotFoundException
    {method} + printPeople(people: ArrayList<String>)
    {method} + inputPeople(input: Scanner, people: ArrayList<String>)
}

@enduml