@startuml
class App{
+Scanner s
+String websiteName
+String name
+String path
+char js
+char css
+File website
+boolean siteMade
---
+ String createIndex(FileWriter filemaker, String name, String websiteName)
        }
@enduml